notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: TMlP1Frss7KQ13/HA//jp30A0zjWYejDAYZHeLbHoZsMtpQZZaUTsQt/o5r5sA3+Gl91Zs5lOmTXfzfeYODevJMwC53CGknZjB01xViUerkU8xvMNecJGv9RmWen9n4ygPD12CIPDi6Ae/hsziCsKi6wh4Jkkol4GqHAHKR8cdlyEwxGN9yUbhN4EmYF6frpOv7L56QXmQDmMfUnak1FKTS11U6C+yHpuR0iOroVpX3R0UYh8ao4tpI9NHMSQmvklu8ZAAjfwehU6Pbo/onW8tr8EAIPOYRRTT7XDluQOtYokXutiw0lZE+bvKyFof715r7T/QzXcfKe4zm/W0tW92HekW9FCkSStnBviOXox3YY5CBmT9Qub/K8SMWOkksl/8piXlwwD4y+ImjXqOi1ZFeLHlJwct7BLQsSTXQMur4XoChc93Plm13kVRZ0Cjk4AA8Et/4yXRVQoheJyAqFu1YqDPNgy84ruWoprRDSbWQYCL7AfP6HkLpFHsLSEMWxluoAQaB4Fyj2jD9CsgHQIJcaNFO5C82GzjsJvqJ5xAOKfDFUhdpAg72WwZM0rg1d3qt0V2pbVNCd2SSPrTFgYNRHUk1/7JJBPkmOnQRJwaFB3aeXpI1x/8rM0NEJ9QtHTmyW5G91CmNRy4AvoFEoos03f5Z9hEpW2SlWxi7ah78=
script:
- mv spec spec.safe
- mkdir spec
- cp spec.safe/runner.js spec/
- curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh
- rm -rf spec
- mv spec.safe spec
- "${APM_SCRIPT_PATH}" install .
- "${APM_SCRIPT_PATH}" link .
- node test

git:
  depth: 10
sudo: false
os:
- linux
- osx
addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
branches:
  only:
  - master
  - develop
  - "/^feature\\/.*$/"
